version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped  # Add this line to specify the restart policy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails runner 'Product.reindex' && bundle exec rails server -b 0.0.0.0"
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ELASTICSEARCH_URL: http://elasticsearch_api:9200 

    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: unless-stopped  # Add this line to specify the restart policy
  
  elasticsearch_api:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

volumes:
  db-data: